import mongoose from 'mongoose';
import { faker } from '@faker-js/faker';
import Patient from '../../../models/Patient.js';
import Physician from '../../../models/Physician.js';
import Prescription from '../../../models/Prescription.js';
import Appointment from '../../../models/Appointment.js';

// --- CONFIG ---
const MONGO = 'mongodb://127.0.0.1:27017/medicalApp';
const OPENAI_KEY = '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'; // Your OpenAI key here

// --- GPT / LLM FUNCTION ---
async function generateWithLLM(prompt) {
  if (!OPENAI_KEY) return `Autogenerated: ${prompt.slice(0, 120)}...`;

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${OPENAI_KEY}`
    },
    body: JSON.stringify({
      model: 'gpt-4',
      messages: [
        { role: 'system', content: 'You are a medical scribe. Keep notes concise, clinical, and realistic and as accurate to your knowledge as a medical professional.' },
        { role: 'user', content: prompt }
      ],
      temperature: 0.7,
      max_tokens: 300
    })
  });
  if (!res.ok) throw new Error(`LLM request failed: ${res.status}`);
  const data = await res.json();
  return data.choices?.[0]?.message?.content?.trim() || '';
}

// --- UTILITY ---
function getAge(dob) {
  const today = new Date();
  let age = today.getFullYear() - dob.getFullYear();
  if (today.getMonth() < dob.getMonth() || (today.getMonth() === dob.getMonth() && today.getDate() < dob.getDate())) age--;
  return age;
}

// Generate medications via LLM
async function generateMedications(age, gender, count = 3) {
  const prompt = `Generate ${count} realistic medications for a ${age}-year-old ${gender} patient with common chronic conditions. Return as comma-separated names.`;
  try {
    const response = await generateWithLLM(prompt);
    const meds = response.split(',').map(m => m.trim()).filter(m => m);
    return meds.length >= count ? meds.slice(0, count) : meds.length > 0 ? meds : ['Lisinopril', 'Metformin', 'Atorvastatin'];
  } catch {
    return ['Lisinopril', 'Metformin', 'Atorvastatin'];
  }
}

// Generate diagnoses via LLM
async function generateDiagnoses(age, gender, count = 4) {
  const prompt = `Generate ${count} realistic diagnoses for a ${age}-year-old ${gender} patient, including ICD-10 codes, description, chronic true/false. Return as JSON array like [{"code":"I10","description":"Hypertension","chronic":true}].`;
  try {
    const response = await generateWithLLM(prompt);
    const parsed = JSON.parse(response);
    if (Array.isArray(parsed)) return parsed.slice(0, count);
  } catch {}
  return [
    { code: 'I10', description: 'Essential hypertension', chronic: true },
    { code: 'E11', description: 'Type 2 diabetes mellitus', chronic: true },
    { code: 'J45', description: 'Asthma', chronic: true }
  ];
}

// --- SEED FUNCTION ---
async function seed({ patients = 5, physicians = 3, maxPrescriptions = 4, maxAppointments = 6 } = {}) {
  await mongoose.connect(MONGO, { dbName: 'medicalApp' });
  console.log('Connected to', MONGO);

  await Patient.deleteMany({});
  await Physician.deleteMany({});
  await Prescription.deleteMany({});
  await Appointment.deleteMany({});

  // Create physicians
  const physicianDocs = [];
  for (let i = 0; i < physicians; i++) {
    const doc = new Physician({
      name: faker.person.fullName(),
      specialization: faker.helpers.arrayElement(['Cardiology', 'Dermatology', 'Endocrinology', 'General Practice']),
      contactInfo: { phone: faker.phone.number(), email: faker.internet.email() },
      schedule: []
    });
    await doc.save();
    physicianDocs.push(doc);
  }

  // Create patients
  for (let i = 0; i < patients; i++) {
    const patient = new Patient({
      name: faker.person.fullName(),
      dob: faker.date.birthdate({ min: 1940, max: 2005, mode: 'year' }),
      gender: faker.person.sex(),
      contactInfo: { phone: faker.phone.number(), email: faker.internet.email(), address: faker.location.streetAddress() }
    });
    await patient.save();

    const age = getAge(patient.dob);

    // Generate diagnoses & medications via LLM
    const diagnoses = await generateDiagnoses(age, patient.gender);
    const medications = await generateMedications(age, patient.gender);

    // Create prescriptions
    const rxCount = faker.number.int({ min: 1, max: maxPrescriptions });
    for (let r = 0; r < rxCount; r++) {
      const med = faker.helpers.arrayElement(medications);
      const dosage = `${faker.number.int({ min: 5, max: 800 })} mg`;
      const instructionsPrompt = `Write concise prescription instructions for ${med} ${dosage} for a ${age}-year-old ${patient.gender} patient, include route & frequency.`;
      const instructions = await generateWithLLM(instructionsPrompt).catch(() => `Take ${dosage} as directed.`);

      const pres = new Prescription({
        patientID: patient._id,
        physicianID: faker.helpers.arrayElement(physicianDocs)._id,
        medicationName: med,
        dosage,
        instructions,
        startDate: faker.date.past({ years: 2 }),
        endDate: null,
        status: 'active'
      });
      await pres.save();
    }

    // Create appointments
    const apptCount = faker.number.int({ min: 1, max: maxAppointments });
    for (let a = 0; a < apptCount; a++) {
      const diagnosis = faker.helpers.arrayElement(diagnoses); // LLM-based
      const notesPrompt = `Write a short clinical visit note for a ${age}-year-old ${patient.gender} patient presenting for follow-up of ${diagnosis.description}. Include assessment and plan, concise clinical language, under 200 words.`;
      const notes = await generateWithLLM(notesPrompt).catch(() => `${diagnosis.description} - follow-up. Stable.`);

      const appt = new Appointment({
        patientID: patient._id,
        physicianID: faker.helpers.arrayElement(physicianDocs)._id,
        date: faker.date.recent({ days: 365 }),
        notes,
        summary: `${diagnosis.description} follow-up`,
        diagnoses: [diagnosis]
      });
      await appt.save();
    }

    console.log(`Seeded patient ${patient._id} (${patient.name})`);
  }

  await mongoose.disconnect();
  console.log('Seeding complete.');
}

// --- RUN SCRIPT ---
if (process.argv[1].endsWith('seed.js')) {
  const patients = process.argv[2] ? Number(process.argv[2]) : 5;
  seed({ patients }).catch(err => {
    console.error('Seed failed:', err);
    process.exit(1);
  });
}
